### ISSUE TITLE
Simple app to display a deBInfer example

### ISSUE THREAD

**Issue by f-lukas** [Pandora-IsoMemo/deBInferS#1]
Subticket for https://github.com/Pandora-IsoMemo/drat/issues/40

**Comment by arunge** [comment]
@f-lukas Please, finish last steps of deployment of the example app and close here. This will make it easier to continue with this task later. Thanks!

**Comment by f-lukas** [comment]
A [main](https://pandoraapp.earth/app/debinfers) and [beta](https://pandoraapp.earth/app/debinfers-beta) version containing a minimal example is now deployed.
